#!/bin/bash

apt update
apt install --yes make git ethtool htop libgtest-dev python3-pip ibverbs-providers ibverbs-utils libibverbs-dev libhugetlbfs0 zlib* ncat unzip zip infiniband-diags libmnl-dev pkgconf* libibumad-dev libpci-dev autoconf libtool apt-file
pip3 install --user meson pyelftools ninja gdown
export PATH=/root/.local/bin:${PATH}

wget https://www.mellanox.com/downloads/MFT/mft-4.26.1-3-x86_64-deb.tgz
gdown 1wDKwiGTvAV1XntzzAw8lJf4J9cnQCQYL

rm -rf ./stage
mkdir ./stage
cd ./stage
tar zxf ../MLNX*tgz
cd MLNX*
./mlnxofedinstall --force
cd ~

rm -rf ./stage1
mkdir ./stage1
cd ./stage1
tar zxvf ../mft*tgz
cd mft*
./install.sh --oem
cd ~

mst start
mlxconfig -y -d /dev/mst/mt4119_pciconf0.1 set SRIOV_EN=1 NUM_OF_VFS=8
echo reboot now
