#!/bin/bash

cd ~

apt update
apt install --yes make git ethtool htop libgtest-dev python3-pip zlib* ncat unzip zip pkgconf* libpci-dev autoconf libtool apt-file socat cmake arping gdb wireshark tshark
pip3 install --user meson pyelftools ninja gdown scapy
export PATH=/root/.local/bin:${PATH}

echo
read -p "Enable IOMMU: 'intel_iommu=on iommu=pt' and update-grub: "
vi /etc/default/grub
update-grub

echo
read -p "Update /etc/network/interfaces: "

echo "set expandtab" > ~/.vimrc
echo "set tabstop=2" >> ~/.vimrc
echo "set shiftwidth=2" >> ~/.vimrc
echo "set bg=dark" >> ~/.vimrc
echo "set noautoindent" >> ~/.vimrc
echo "set nosmartindent" >> ~/.vimrc
echo "set nocindent" >> ~/.vimrc
echo "set wrap" >> ~/.vimrc
echo ":syntax off" >> ~/.vimrc
echo ":set colorcolumn=120" >> ~/.vimrc
echo "alias edit=vi" >> ~/.bashrc

echo
echo reboot now
