#!/bin/bash -ex

# This script is indempotent. You should be able to run it
# multiple times and get to the same end state

#
# Where GIT repos will be cloned and built
#
export H=${HOME}/Dev
mkdir -p $H

#
# Where the DPDK libraries, headers are installed
# If you change this, also update:
#  $H/reinvent/CMakeLists.txt in two places (-I, -L instructions)
#
export D=${HOME}/local
mkdir -p $D
export LD_LIBRARY_PATH=${D}/lib64:${LD_LIBRARY_PATH}
export PKG_CONFIG_PATH=${D}/lib64/pkgconfig:${PKG_CONFIG_PATH}

#
# Install some of the prereqs
#
sudo /usr/bin/amazon-linux-extras
sudo yum install make numactl-libs.x86_64 numactl-devel.x86_64 rdma-core-devel.x86_64 git ethtool gcc-c++.x86_64 gtest-devel.x86_64 gtest-.x86_64
pip3 install --user meson pyelftools ninja

# sudo yum install cmake too old
# install cmake without yum
cd $H
rm -rf ./cmake-3.22.1-linux-x86_64
wget https://cmake.org/files/v3.22/cmake-3.22.1-linux-x86_64.sh
chmod 500 cmake-3.22.1-linux-x86_64.sh
# this unpacks and installs cmake. Accept license and answer 'Y' to install under cmake-3.22.1-linux-x86_64 dir
./cmake-3.22.1-linux-x86_64.sh
rm -f cmake-3.22.1-linux-x86_64.sh
export PATH=${H}/cmake-3.22.1-linux-x86_64/bin:${PATH}

#
# Clone repos 
# 
cd $H
rm -rf ./dpdk
git clone git://dpdk.org/dpdk
rm -rf ./reinvent
git clone https://github.com/rodgarrison/reinvent.git
sudo rm -rf ./amzn-drivers
git clone https://github.com/amzn/amzn-drivers.git

#
# Install Amazon driver updates for DPDK
#
cd $H/amzn-drivers/userspace/dpdk/enav2-vfio-patch
sudo ./get-vfio-with-wc.sh

#
# Build and install DPDK
#
cd $H/dpdk
meson -Db_lto=true -Dplatform=native -Dprefix=${D} build
# Note: running too many jobs will exhaust tmp space due to LTO
ninja -j 10 -C build install

#
# Build reinvent
#
cd $H/reinvent
mkdir build
cd build
cmake -DUNIT_TEST=ON -DINTEGRATION_TEST=ON ..
make -j 10

#
# Add variables to ~/.bashrc
#
echo "export H=${H}" >> ${HOME}/.bashrc
echo "export D=${D}" >> ${HOME}/.bashrc
echo "export LD_LIBRARY_PATH=${D}/lib64" >> ${HOME}/.bashrc
echo "export PKG_CONFIG_PATH=${D}/lib64/pkgconfig" >> ${HOME}/.bashrc
echo "export PATH=${H}/cmake-3.22.1-linux-x86_64/bin:${PATH}" >> ${HOME}/.bashrc
