#!/usr/bin/python3

sizes = [1, 64, 128, 512, 1024, 1048576, 50*1048576, 100*1048576, 500*1048576, 1073741824]

for sz in sizes:
  fn = "ncat_payload_{0}_bytes".format(sz)
  print("writing {0}".format(fn))
  fid = open(fn, "w")
  i=0
  if i<1024:
    while i<sz:
      fid.write("A");
      i=i+1
  else:
    data = 'A'*1024
    while i<sz:
      fid.write("{0}",data);
      i=i+1024
  fid.close()
