#!/bin/bash

#
# run as sudo
#

echo Typical first time commands:
echo 1. show port info 0
echo
echo

TASK="${H}/dpdk/build/app/dpdk-testpmd"
ARGS="--proc-type primary --in-memory --log-level 7 -n 12 --allow 01:00.1,class=eth -- -i"
$TASK $ARGS
