#!/bin/bash

#
# run as sudo
#

echo Typical first time commands:
echo 1. show port info 0
echo
echo

TASK="${H}/dpdk/build/app/dpdk-testpmd"

# rhs arg '--eth-link-speed 25000' suppressed; set via ethtool in setup
ARGS="--proc-type primary --in-memory --log-level 7 -n 12 -l 4,5,6,7,8 --allow 01:00.1,class=eth -- -i --numa --port-numa-config=(0,0) --ring-numa-config=(0,3,0)"

$TASK $ARGS
