#!/bin/bash

#
# Run this script as ROOT once following machine reboot or restart
#

umount /dev/hugepages
umount /mnt/huge
echo 2048 > /sys/devices/system/node/node0/hugepages/hugepages-2048kB/nr_hugepages
echo 2048 > /sys/devices/system/node/node1/hugepages/hugepages-2048kB/nr_hugepages
mkdir -p /mnt/huge
mount -t hugetlbfs nodev /mnt/huge
modprobe vfio-pci
python3 ${H}/dpdk/usertools/dpdk-devbind.py -b vfio-pci 7f:00.0
python3 ${H}/dpdk/usertools/dpdk-devbind.py -s
